name: citybike
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.4
  provider: ^6.1.5+1
  google_maps_flutter: ^2.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/outfit/Outfit-Bold.ttf
        - asset: assets/fonts/outfit/Outfit-Regular.ttf
    - family: Work Sans
      fonts:
        - asset: assets/fonts/work_sans/WorkSans-Bold.ttf
        - asset: assets/fonts/work_sans/WorkSans-Regular.ttf
  
